import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
  Converter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  Converter_Container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#292929",
    opacity: 70,
    width: "95%",
    marginTop: "1%",
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  Converter_Item: {
    flex: 4,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    paddingTop: 20,
    paddingHorizontal: 5,
  },
  Converter_Image: {
    flex: 9,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  Item_Image: {
    position: "absolute",
    alignSelf: "center",
  },
  bgImage: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  Converter_Point: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  Converter_Point_Bar: {
    flex: 3,
    marginHorizontal: 5,
  },
  Converter_Point_Text: {
    flex: 1,
    color: "#c8a152",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    fontSize: 8,
    fontWeight: "bold",
  },
  Converter_Point_Box: {
    flex: 1,
    flexDirection: "row",
    position: "absolute",
    right: 0,
    bottom: 0,
  },
  Converter_Point_Image: {
    height: 50,
    paddingHorizontal: 10,
    paddingVertical: 5,
    margin: 5,
    resizeMode: "contain",
  },
  Converter_Point_Button: {
    height: 50,
    paddingHorizontal: 10,
    paddingVertical: 5,
    margin: 5,
    justifyContent: "center",
    borderColor: "#171518",
    borderWidth: 5,
    borderRadius: 10,
    shadowColor: "black",
  },
  Converter_Point_Button_Button: {
    borderRadius: 5,
    backgroundColor: "#404040",
    height: "100%",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  Converter_Name: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#302923",
    borderWidth: 3,
    borderColor: "#ffd66a",
    borderRadius: 5,
    width: "100%",
    marginTop: 5,
    fontFamily: "NanumSquare",
  },
  orange_text: {
    fontWeight: "bold",
    color: "#ffd66a",
  },
  // ================  //
  Converter_Option: {
    flex: 6,
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    width: "100%",
  },
  Converter_Part: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    marginBottom: 5,
  },
  Converter_Part_Converter: {
    flex: 6,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    backgroundColor: "#101010",
    borderRadius: 5,
    marginRight: 2,
  },
  Converter_Part_Converter_Converter: {
    flex: 3,
    resizeMode: "contain",
    justifyContent: "center",
    alignItems: "center",
  },
  Converter_Part_Converter_Count: {
    flex: 6,
    color: "#9c9aa5",
    justifyContent: "center",
    alignItems: "center",
  },
  gray_text: {
    color: "#a09fa7",
  },
  orange_text: {
    color: "#fab260",
  },
  Converter_Part_Fix: {
    flex: 4,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#101010",
    borderRadius: 5,
    marginLeft: 2,
  },
  Option_Part: {
    flex: 3,
    flexDirection: "column",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "black",
    borderRadius: 10,
    marginBottom: 5,
    paddingBottom: 5,
  },
  Option_Head: {
    flex: 1,
    width: "99%",
    flexDirection: "row",
    marginVertical: 4,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  Option_Head_Text: {
    color: "#a1a0a6",
    textShadowColor: "black",
    textShadowRadius: 4,
  },
  Start_Part: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  // ====================== //
  startbutton: {
    width: "65%",
    borderRadius: 5,
    paddingVertical: 10,
    backgroundColor: "#4a454b",
    justifyContent: "center",
    alignItems: "center",
  },
  starttext: {
    color: "#a7a3b2",
    textShadowColor: "black",
    textShadowRadius: 4,
  },
  // ====================== //
  OptionTableHead: {
    fontWeight: "bold",
    fontSize: 30,
    marginTop: 30,
  },
  OptionTableBtn: {
    width: "30%",
    borderRadius: 10,
    paddingVertical: 10,
    marginVertical: 30,
    backgroundColor: "#4a454b",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
  },
  OptionTableText: {
    color: "white",
  },
});

export const ButtonStyles = StyleSheet.create({
  button: {
    width: "90%",
    paddingVertical: 5,
    marginVertical: 3,
    borderRadius: 5,
    backgroundColor: "#fad15d",
    justifyContent: "center",
    alignItems: "center",
  },
  text: {
    color: "#fff",
    textShadowColor: "black",
    textShadowRadius: 2,
  },
});

export const OptionStyles = StyleSheet.create({
  Option_Btn: {
    flex: 1,
    width: "90%",
    flexDirection: "row",
    marginVertical: 4,
    backgroundColor: "#3b393c",
    borderRadius: 12,
    justifyContent: "space-between",
    alignItems: "center",
  },
  Option_Btn_Selected: {
    flex: 1,
    width: "90%",
    flexDirection: "row",
    marginVertical: 4,
    backgroundColor: "#2c282d",
    borderRadius: 12,
    justifyContent: "space-between",
    alignItems: "center",
  },
  Option_Icon: {
    marginRight: 10,
    fontWeight: "bold",
    color: "#101010",
    textShadowColor: "black",
    textShadowRadius: 4,
  },
  Option_Icon_Selected: {
    marginRight: 10,
    fontWeight: "bold",
    color: "#a29eac",
    textShadowColor: "#a29eac",
    textShadowRadius: 4,
  },
  Option_Text: {
    marginLeft: 10,
    fontWeight: "bold",
    color: "#a29eac",
    textShadowColor: "black",
    textShadowRadius: 10,
  },
});

export const ModalStyles = StyleSheet.create({
  ModalStyle: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
});

export const HomeStyles = StyleSheet.create({
  Home: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    paddingBottom: 10,
  },
  Home_Head: {
    flex: 2,
    width: "80%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "contain",
  },
  Home_Button: {
    flex: 2,
    flexDirection: "row",
    width: "80%",
    borderRadius: 10,
    marginVertical: 10,
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "contain",
  },
  Home_Text: {
    color: "black",
    fontSize: 25,
    fontWeight: "bold",
  },
  Home_Help_Button: {
    position: "absolute",
    right: 0,
    top: 0,
    margin: 10,
  },
  Home_Modal: {
    flex: 1,
  },
  Home_Help: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  Home_Image: {
    flex: 1,
    resizeMode: "contain",
    height: "85%",
    width: "85%",
  },
  Home_Settings_box: {
    flex: 1,
    width: "80%",
    flexDirection: "row",
    marginVertical: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  Home_Settings_btn: {
    flex: 1,
    flexDirection: "row",
    width: "80%",
    height: "100%",
    borderRadius: 10,
    marginVertical: 10,
    marginHorizontal: 5,
    justifyContent: "center",
    alignItems: "center",
  },
});

export const AkashicStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "gray",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: "3%",
    marginVertical: "1%",
    borderRadius: 15,
  },
  akashic_head: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "80%",
  },
  akashic_head_btn: {
    marginHorizontal: 10,
  },
  my_list_container: {
    flex: 7,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  my_list_box: {
    flex: 1,
    width: "90%",
    marginTop: "5%",
    marginBottom: "5%",
    borderWidth: 5,
    borderColor: "#ebd89d",
    borderTopWidth: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    textAlign: "center",
  },
  bgImage: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "cover",
  },
  akashic_function_container: {
    flex: 1,
    flexDirection: "row",
    width: "90%",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  akashic_function_box: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    backgroundColor: "yellow",
  },
  akashic_btn_container: {
    flex: 2,
    flexDirection: "row",
    backgroundColor: "#454442",
    borderColor: "black",
    borderWidth: 3,
    borderRadius: 15,
    shadowColor: "black",
    shadowRadius: 100,
    elevation: 10,
    marginVertical: 10,
    marginHorizontal: 20,
    resizeMode: "contain",
  },
  akashic_btn: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "contain",
  },
  akashic_btn_image: {
    borderRadius: 5,
  },
  used_akashic_container: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#180d15",
    borderRadius: 10,
    margin: 5,
    paddingHorizontal: 5,
  },
  used_akashic_col_image: {
    flex: 1,
    height: "100%",
    width: "100%",
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    resizeMode: "contain",
  },
  used_akashic_col: {
    justifyContent: "center",
    alignItems: "center",
  },
  used_akashic_col_text: {
    color: "#e3c57c",
    textAlign: "center",
  },
  modal: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "contain",
  },
  bgImage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "contain",
  },
  button: {
    flex: 1,
    paddingVertical: 10,
    marginHorizontal: 10,
    borderRadius: 5,
    backgroundColor: "#fad15d",
    justifyContent: "center",
    alignItems: "center",
  },
});

export const BroochStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "gray",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: "3%",
    marginVertical: "1%",
    borderRadius: 15,
  },
  brooch_head: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "80%",
  },
  my_list_container: {
    flex: 16,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  my_list_box: {
    flex: 1,
    width: "90%",
    marginTop: "5%",
    marginBottom: "5%",
    borderWidth: 5,
    borderColor: "#ebd89d",
    borderTopWidth: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    textAlign: "center",
  },
  bgImage: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "cover",
  },
  brooch_btn_container: {
    flex: 3,
    flexDirection: "row",
    backgroundColor: "#454442",
    borderColor: "black",
    borderWidth: 3,
    borderRadius: 15,
    shadowColor: "black",
    shadowRadius: 100,
    elevation: 10,
    marginVertical: 10,
    marginHorizontal: 20,
    resizeMode: "contain",
  },
  brooch_btn: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    resizeMode: "contain",
  },
  brooch_btn_image: {
    borderColor: "gray",
    borderWidth: 2,
    borderRadius: 5,
  },
  used_brooch_container: {
    flex: 2,
    flexDirection: "row",
    backgroundColor: "#180d15",
    borderRadius: 10,
    margin: 5,
    paddingHorizontal: 5,
  },
  used_brooch_col_image: {
    flex: 1,
    height: "100%",
    width: "100%",
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    resizeMode: "contain",
  },
  used_brooch_col: {
    justifyContent: "center",
    alignItems: "center",
  },
  used_brooch_col_text: {
    color: "#e3c57c",
    textAlign: "center",
  },
  modal_head: {
    flex: 4,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  modal_body: {
    flex: 4,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  modal_foot: {
    flex: 3,
    flexDirection: "row",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  modal_image_full: {
    width: "50%",
    height: "50%",
    resizeMode: "cover",
  },
  used_brooch_col: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});

export const BroochButtonStyles = StyleSheet.create({
  button: {
    flex: 1,
    paddingVertical: 10,
    marginHorizontal: 10,
    borderRadius: 5,
    backgroundColor: "#fad15d",
    justifyContent: "center",
    alignItems: "center",
  },
  text: {
    color: "#fff",
    textShadowColor: "black",
    textShadowRadius: 2,
    elevation: 10,
  },
});

export const SettingStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  head: {
    flex: 1,
  },
  box: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  text: {
    fontWeight: "bold",
    fontSize: 24,
    marginHorizontal: 10,
  },
});
